# -*- coding: utf-8 -*-
"""analise.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4xRYp5wobVUSGy0kwGwBb7bTHQMou5S
"""

import pandas as pd

# Ler o arquivo CSV
df = pd.read_csv("vendas_silver.csv")

# Mostrar os dados carregados
print("Dados carregados:")
print(df)

# Calcular total de vendas
total_vendas = df["valor"].sum()

# Exibir o total de vendas
print("\nTotal de vendas:")
print(total_vendas)