# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjY8tK2rvRfH4FVP0Odsie_qSbz5ZEvG
"""

from google.colab import files
import pandas as pd
from IPython.display import display

uploaded = files.upload()
df = pd.read_csv("produtos.csv")
display(df)

# Usar a primeira fila como header
df.columns = df.iloc[0]
df = df[1:].copy()

# Renomear colunas
df.columns = ["produto", "valor"]

# Remover nulos ANTES de convertir a string
df = df.dropna(subset=["produto"])

# Limpar texto primeiro
df["produto"] = df["produto"].astype(str).str.strip().str.lower()

# Mapear texto para número
mapa_numeros = {
    "zero": 0,
    "um": 1,
    "dois": 2,
    "tres": 3
}

df["valor"] = df["valor"].replace(mapa_numeros)

# Converter para número
df.loc[:, "valor"] = pd.to_numeric(df["valor"], errors="coerce")

# Remover nulos
df = df.dropna()

# Remover negativos
df = df[df["valor"] >= 0]

# Remover inválidos
df = df[df["produto"].str.isalpha()]

# Agrupar
df = df.groupby("produto")["valor"].sum().reset_index()

display(df)